[compatibility_flags]
nodejs_compat = true

# Configuración para Pages
[site]
bucket = ".next"  # Directorio de salida de Next.js

# Configuración específica para Pages
[build]
command = "npm run build"
[build.upload]
format = "service-worker"

# Configuración de rutas
[env.production]
routes = [
  { pattern = "/*", zone_name = "home-market-landing-page.pages.dev" }
]

# Opcional: Si necesitas configuraciones adicionales para Pages 